version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          context: mycontext
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          profile-name: default
          region: AWS_REGION
          repo: ecrrepo
          skip-when-tags-exist: false
          tag: '${CIRCLE_SHA1}'
