version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: https://592678693542.signin.aws.amazon.com/console
          aws-access-key-id: ${AccessKey}
          aws-secret-access-key: ${SecrectKey}
          context: myContext
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ../Dockerfile
          profile-name: default
          region: us-east-1
          repo: testrepo
          skip-when-tags-exist: false
          tag: 'latest,myECRRepoTag'
